config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#index'
  get 'posts/beautypage' => 'posts#beautypage'
  get 'posts/troublepage' => 'posts#troublepage'
  resources :users, only: [:edit, :update] 
  resources :posts, only: [:new, :create] 
end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択して下さい' },
    { id: 2, name: '10代' },
    { id: 3, name: '20代' },
    { id: 4, name: '30代' },
    { id: 5, name: '40代' },
    { id: 6, name: '50代' },
    { id: 7, name: '60代' },
    { id: 8, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bodypart.rb
class Bodypart < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択して下さい' },
    { id: 2, name: '全身' },
    { id: 3, name: '頭' },
    { id: 4, name: '髪' },
    { id: 5, name: '顔' },
    { id: 6, name: '腕' },
    { id: 7, name: '手' },
    { id: 8, name: '爪' },
    { id: 9, name: '胸' },
    { id: 10, name: '腹' },
    { id: 11, name: '尻' },
    { id: 12, name: '足' },
    { id: 13, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :posts

end

app/models/freeword.rb
class Freeword < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択して下さい' },
    { id: 2, name: '脱毛' },
    { id: 3, name: '美肌' },
    { id: 4, name: 'UVケア' },
    { id: 5, name: 'ネイル' },
    { id: 6, name: '化粧' },
    { id: 7, name: 'ニキビ' },
    { id: 8, name: 'アトピー' },
    { id: 9, name: 'スタイリング' },
    { id: 10, name: '美容食品' }
  ]

  include ActiveHash::Associations
  has_many :posts

end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択して下さい' },
    { id: 2, name: '美容投稿' },
    { id: 3, name: 'お悩み投稿' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :age
  belongs_to :bodypart
  belongs_to :skin
  belongs_to :freeword


  with_options presence: true do
    validates :title, length: { maximum: 50 }
    validates :detail
    validates :user_id
    validates :genre_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :age_id, numericality: { other_than: 1, message: "can't be blank" } 
    validates :bodypart_id, numericality: { other_than: 1, message: "can't be blank" } 
  end
end

app/models/skin.rb
class Skin < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択して下さい' },
    { id: 2, name: '乾燥肌' },
    { id: 3, name: 'アトピー肌' },
    { id: 4, name: 'オイリー肌' },
    { id: 5, name: '混合肌' },
    { id: 6, name: '普通肌' }
  ]

  include ActiveHash::Associations
  has_many :posts

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Include both letters and numbers.'
    validates :nickname, length: { maximum: 6 }
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def beautypage
    @beautypages = Post.where(genre_id: 2)
  end

  def troublepage
    @troublepages = Post.where(genre_id: 3)
  end


  private 

  def post_params
    params.require(:post).permit(:title, :detail, :genre_id, :age_id, :bodypart_id, :skin_id, :freeword_id, images: []).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<main class="main">
  <div class='title-contents'>
    <div class='store-btn'>
      <%= link_to image_tag("beauty-post.png", class:"apple-btn"), posts_beautypage_path %>
      <%= link_to image_tag("consult-post.png", class:"google-btn"), posts_troublepage_path %>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Polishan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("polishine-logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right"> 
              <%= link_to current_user.nickname, edit_user_path(current_user), class: "user-nickname" %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "投稿する", new_post_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, id: 'new_post', local: true do |f|%>
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title, id:"post_title" %>
  </div>

  <div class="field">
    <%= f.label :images, "画像" %><br />
    <p>
      クリックしてファイルをアップロード
    </p>
    <%= f.file_field :images, multiple: true, id:"post_image" %>
  </div>

  <div class="field">
    <%= f.label :genre_id, "投稿ジャンル" %><br />
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box"}) %>
  </div> 

  <div class="field">
    <%= f.label :detail, "投稿内容" %><br />
    <%= f.text_area :detail, class: :form__text, id:"post_detail" %>
  </div>

  <div class="field">
    <%= f.label :age_id, "年齢" %><br />
    <%= f.collection_select(:age_id, Age.all, :id, :name, {}, {class:"select-box"}) %>
  </div>

  <div class="field">
    <%= f.label :bodypart_id, "部位" %><br />
    <%= f.collection_select(:bodypart_id, Bodypart.all, :id, :name, {}, {class:"select-box"}) %>
  </div>

  <div class="field">
    <%= f.label :skin_id, "肌質" %><br />
    <%= f.collection_select(:skin_id, Skin.all, :id, :name, {}, {class:"select-box"}) %>
  </div>

  <div class="field">
    <%= f.label :freeword_id, "フリーワード" %><br />
    <%= f.collection_select(:freeword_id, Freeword.all, :id, :name, {}, {class:"select-box"}) %>
  </div>

  <div class="actions">
    <%= f.submit "投稿", class: :form__btn  %>
  </div>
<% end %>

app/views/posts/beautypage.html.erb
<div class='post-contents'>
  <h1 class='title'>美容投稿</h1>
  <div clss='post'>
    <% @beautypages.each do |t| %>
    <div class='post-list'>
      <div class='post-img-content'>
        <% t.images.each do |image| %>
          <%= link_to image_tag(image, width:200, class: :post__img), root_path %>
        <% end %>
      </div>
      <div class='post-title'>
        <%= link_to t.title, root_path, class: :post__title %>
      </div>
      <%= link_to t.user.nickname, root_path, class: :post__user %>さん
    </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規投稿</h2>
        <%= render partial: "form", locals: {url: posts_path, method: :post}%>
    </div>
  </div>
</div>

app/views/posts/troublepage.html.erb
<div class='post-contents'>
  <h1 class='title'>お悩み投稿</h1>
  <div clss='post'>
    <% @troublepages.each do |t| %>
    <div class='post-list'>
      <div class='post-img-content'>
        <% t.images.each do |image| %>
          <%= link_to image_tag(image, width:200, class: :post__img), root_path %>
        <% end %>
      </div>
      <div class='post-title'>
        <%= link_to t.title, root_path, class: :post__title %>
      </div>
      <%= link_to t.user.nickname, root_path, class: :post__user %>さん
    </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", "#", class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :nickname%>
          </div>
          <div class='field-input'>
            <%= f.text_field :nickname, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>